//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int Id { get; set; }
        public string IdNews { get; set; }
        public string Author { get; set; }
    }
}
