//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table3
    {
        public int Id2 { get; set; }
        public string IdNews2 { get; set; }
        public string Picture { get; set; }
        public string Path { get; set; }
    }
}
