//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table2
    {
        public int Id1 { get; set; }
        public string IdNews1 { get; set; }
        public string LikeCount { get; set; }
        public string RepostCount { get; set; }
        public string Viewes { get; set; }
        public string Time { get; set; }
        public string Text { get; set; }
    }
}
